name: GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Clojure tools
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
        
    - name: Create public directory
      run: |
        mkdir -p public
        
    # - name: Build ClojureScript
    - name: Build ClojureScript (Development Mode)
      run: |
        npm install shadow-cljs -g
        npm install
        npx shadow-cljs compile app --verbose
       # npx shadow-cljs release app --verbose
        
    - name: Copy static assets
      run: |
        cp -r resources/public/* public/ || true
        
    - name: List contents for debugging
      run: |
        echo "Contents of public/js:"
        ls -la public/js/
        echo "Contents of public/js/cljs-runtime (if exists):"
        ls -la public/js/cljs-runtime/ || true
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
        branch: gh-pages 